### ISSUE TITLE
Is there code folding option in Rich text editor ?

### ISSUE THREAD

**Issue by Pooja-Bhargavi** [TomasMikula/RichTextFX#451] opened 2017-03-14 06:36 UTC
Is there an option for code folding in rich text editor. ? If its already there be a demo program to explain it ?

**Comment by kuc** [comment] 2017-03-14 09:56
Duplicate of #107

**Comment by JordanMartinez** [comment] 2017-03-17 01:00
Closing as this is a duplicate issue.

**Closed by JordanMartinez** 2017-03-17 01:00 UTC
