### ISSUE TITLE
Memory Leak may happen when load a large text.

### ISSUE THREAD

**Issue by XDean** [TomasMikula/RichTextFX#409] opened 2016-12-23 05:35 UTC
Hi Tomas.
I used CodeArea(0.7-M2) and set a large text about 20M to it. And then memory leak happened.

![leak1](https://cloud.githubusercontent.com/assets/12760952/21447721/f5bea946-c913-11e6-930b-c48feeec7817.png)
![leak2](https://cloud.githubusercontent.com/assets/12760952/21447722/f8233c7e-c913-11e6-95d1-18bddebcabcf.png)

**Comment by kuc** [comment] 2016-12-23 08:58
20 MB of text loaded into String occupies about 50 MB - seems about right: `char` in Java is 2-bytes long.
Not sure about `ReadOnlyStyledDocument`.

**Comment by XDean** [comment] 2016-12-28 09:56
@kuc You are right, the second problem may be the text itself.

**Comment by TomasMikula** [comment] 2017-03-03 05:25
If the text has about 670,000 lines, then the object counts seem about right.

`ReadOnlyStyledDocument` uses a balanced tree where the leaves are lines and each internal node has 2 or 3 child nodes. The nodes contain information for fast conversion between _(row, column)_ coordinates and absolute number of characters. It also allows insertion/deletion in the middle of the document without extensive memory copying.

The tree will have as many leaf nodes (`Leaf`) as there are lines. There are ~677,000 leaf nodes. The number of internal nodes (`Branch`) will be anywhere between 50% (when most internal nodes have 3 children) and 100% (when most internal nodes have 2 children) of the number of leaf nodes. There are ~340,000 `Branch` nodes, which is closer to the 50%. Each internal node has a linked list of child nodes. `Cons` is a node of the linked list. Since every node in the tree except the root is be pointed to from a linked list, there are as many `Cons` objects as the total number of nodes in the tree. There are ~1,017,000 `Cons` nodes. The numbers seem to add up as they should.

Could this be improved? Since by design every internal node has either 2 or 3 child nodes, we could have two specialized versions of internal nodes, `Branch2` and `Branch3`, where the child nodes are stored directly as members, instead of allocating a linked list of children. This would reduce the number of objects needed by the tree by half, but the total memory of the tree overhead by less than half. At the expense that a lot of code in the tree implementation has to be written twice (for Branch2 and Branch3). Anyway the `Cons` nodes seem to amount to only ~24 MB, so not a huge win.

The most memory in your application is consumed by `String`s. There is at least one string per line, and more if the line contains segments of different style.

**Comment by JordanMartinez** [comment] 2017-03-03 05:55
> The most memory in your application is consumed by Strings. There is at least one string per line, and more if the line contains segments of different style.

And won't this improve in Java 9 with the String duduplication feature enabled by default?

**Comment by TomasMikula** [comment] 2017-03-03 06:02
If there are a lot of duplicate strings... This could well be the case for source code, where the same words are repeated a lot.

**Comment by JordanMartinez** [comment] 2017-05-30 00:46
Since the issues raised here seem addressed (or at least explained), I'm closing this.

**Closed by JordanMartinez** 2017-05-30 00:46 UTC
