### ISSUE TITLE
How to set default text color with word highlighting of CodeArea?

### ISSUE THREAD

**Issue by KnightPL** [TomasMikula/RichTextFX#442] opened 2017-02-09 13:40 UTC
I want to color the words which have not yet been colored with word highlightning (patterns etc.)
I tried:
```
CodeArea codeArea = new CodeArea();
codeArea.setId("codearea");
```
and in .css file
```
#codearea .text {
    -fx-fill: whitesmoke;
}
```
but it colors all text in CodeArea
Any ideas or help ?
Sorry about my bad english :)
Thanks

**Comment by JordanMartinez** [comment] 2017-02-10 01:57
If I'm understanding you correctly, you want to do the following, right:

1. Create a CodeArea 
2. Make all of that area's text styled to a "regular text" style at its starting state.
3. As time goes on, calculate what text in the area (according some some pattern) should now be styled to "highlight text"
4. As time goes on, any "highlight text"-styled text should not be restyled back to "regular text" style if it no longer adheres to some pattern.

**Comment by KnightPL** [comment] 2017-02-10 10:04
So, first i create CodeArea object, set id (style from css file), then I add highlightning 
```
        codeArea = new CodeArea();
        codeArea.setId("codearea");
        codeArea.richChanges()
                .filter(ch -> !ch.getInserted().equals(ch.getRemoved()))
                .subscribe(change -> {
                    codeArea.setStyleSpans(0, computeHighlighting(codeArea.getText().toLowerCase()));
                });
```

But still all text is colored :( Maybe Im doing something wrong

![obraz](https://cloud.githubusercontent.com/assets/13942623/22822511/0e4562b0-ef80-11e6-901d-ca389873a493.png)

Here highlightning (without dark background):

![obraz](https://cloud.githubusercontent.com/assets/13942623/22822571/4718d13a-ef80-11e6-9732-65965708edd3.png)

I need to color rest of text, i dont have already any ideas how to do that :(
Thanks :)

**Comment by JordanMartinez** [comment] 2017-02-10 21:33
What happens if you don't set the area's ID? Does the highlighting work then? 

And what does your `computeHighlighting` method's innards look like?

**Comment by KnightPL** [comment] 2017-02-10 21:46
> What happens if you don't set the area's ID? Does the highlighting work then?

It works, but default is black color and dark background need white text or something. (I need dark background so...)

computeHighlighting is method from here: 
[https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywords.java](url)

```
private static StyleSpans<Collection<String>> computeHighlighting(String text) {
        Matcher matcher = PATTERN.matcher(text);
        int lastKwEnd = 0;
        StyleSpansBuilder<Collection<String>> spansBuilder
                = new StyleSpansBuilder<>();
        while(matcher.find()) {
            String styleClass =
                    matcher.group("KEYWORD") != null ? "keyword" :
                    matcher.group("PAREN") != null ? "paren" :
                    matcher.group("BRACE") != null ? "brace" :
                    matcher.group("BRACKET") != null ? "bracket" :
                    matcher.group("SEMICOLON") != null ? "semicolon" :
                    matcher.group("STRING") != null ? "string" :
                    matcher.group("COMMENT") != null ? "comment" :
                    null; /* never happens */ assert styleClass != null;
            spansBuilder.add(Collections.emptyList(), matcher.start() - lastKwEnd);
            spansBuilder.add(Collections.singleton(styleClass), matcher.end() - matcher.start());
            lastKwEnd = matcher.end();
        }
        spansBuilder.add(Collections.emptyList(), text.length() - lastKwEnd);
        return spansBuilder.create();
}
```

**Comment by JordanMartinez** [comment] 2017-02-10 22:12
Wait, so you're using the `computeHighlighting` method from the JavaKeywords demo? Have you modified its implementation at all?

**Comment by KnightPL** [comment] 2017-02-10 22:18
Only patterns:

```
private static StyleSpans<Collection<String>> computeHighlighting(String text) {
        Matcher matcher = PATTERN.matcher(text);
        int lastKwEnd = 0;
        StyleSpansBuilder<Collection<String>> spansBuilder
                = new StyleSpansBuilder<>();
        while(matcher.find()) {
            String styleClass =
                    matcher.group("MNEMONIC") != null ? "mnemonic" :
                    matcher.group("REGISTRY") != null ? "registry" :
                    matcher.group("DIRECTIVE") != null ? "directive" :
                    matcher.group("COMMENT") != null ? "comment" :
                    matcher.group("LABEL") != null ? "label" :
                             null; /* never happens */ assert styleClass != null;
            spansBuilder.add(Collections.emptyList(), matcher.start() - lastKwEnd);
            spansBuilder.add(Collections.singleton(styleClass), matcher.end() - matcher.start());
            lastKwEnd = matcher.end();
        }
        spansBuilder.add(Collections.emptyList(), text.length() - lastKwEnd);
        return spansBuilder.create();
    }
```

**Comment by JordanMartinez** [comment] 2017-02-11 16:45
It doesn't seem like you're doing anything wrong. Have you debugged it via ScenicView yet? It does seem clear that the initial CSS overrides the highlighting CSS.

You will probably need to subclass `StyledTextArea` in the same way that `StyleClassedTextArea` does, but modify the `applyStyle` to account for ID-specific CSS.

**Comment by KnightPL** [comment] 2017-02-11 20:10
Ok, thanks for help, I will try ;)

**Comment by liz3** [comment] 2017-02-19 03:18
Same here i think, im trying to set the default, the highlighting works fine.
btw. im not even setting an id.
But the property: `-fx-fill: white` does not change anything, but it is working, trough if i set the property: 
`-fx-background-color: black` just works fine.

**Comment by JordanMartinez** [comment] 2017-02-20 17:10
After looking at this further, I wonder if the issue is the same thing arising from #303, part of which was fixed in #398.

**Comment by liz3** [comment] 2017-02-27 02:13
Yeah, but not the text-color, is there maybe a work around for that issue?

**Comment by JordanMartinez** [comment] 2017-02-28 04:41
@liz3 After looking at it a bit more, I got the default color to work by using the following CSS file:
````css
.styled-text-area {
    -fx-background-color: black;
}
.paragraph-box > .paragraph-text > .text {
    -fx-fill: white;
}
````
Technically, the CSS should be `.styled-text-area > .virtual-flow > .paragraph-box > .paragraph-text > .text { /* CSS */ }` However, this doesn't work. Everything from `paragraph-box` forward works, so I'm not sure why the `virtual-flow` selector screws things up.

**Comment by JordanMartinez** [comment] 2017-02-28 04:55
I've updated the CSS Reference Guide to properly demonstrate the three selector usage to style the default text.

**Comment by JordanMartinez** [comment] 2017-02-28 05:06
Update: I found that if I replaced the `>` to denote immediate children with ` ` to denote within its children, then this CSS string works: 
````css
.styled-text-area {
    -fx-background-color: black;
}
.styled-text-area .virtual-flow .paragraph-box .paragraph-text .text {
    -fx-fill: white;
}
````
Thus, @KnightPL, you can achieve your goal without subclassing the area by using this CSS:
````css
#codearea .virtual-flow .paragraph-box .paragraph-text .text {
    -fx-fill: whitesmoke;
}
````

**Comment by JordanMartinez** [comment] 2017-02-28 05:10
I've updated CSS Ref Guide to include the full selector string

**Comment by JordanMartinez** [comment] 2017-02-28 05:30
Actually... `#codeArea .text { /* CSS */ }` does the same thing as the full string above... I remembered this issue being different from what it actually was. 

Forget what I said in my previous comment, @KnightPL. Instead, I found that this will work:
Given a CSS file like:
````css
.styled-text-area {
    -fx-background-color: black;
}
#someArea .text {
    -fx-fill: white;
}

#someArea .red {
    -fx-fill: red;
}
````
and an application like so:
````java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.fxmisc.flowless.VirtualizedScrollPane;
import org.fxmisc.richtext.CodeArea;

import java.util.Collections;

public class CssBug extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {

        CodeArea area = new CodeArea("initial text");
        VirtualizedScrollPane<CodeArea> vsPane = new VirtualizedScrollPane<>(area);
        area.setId("someArea");
        area.setStyle(6, area.getLength(), Collections.singleton("red"));

        Scene scene = new Scene(vsPane, 500, 200);
        scene.getStylesheets().addAll(CssBug.class.getResource("css-bug.css").toExternalForm());


        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
            launch(args);
        }
}
````
I can override the default `whitesmoke` fill with a `red` fill.

**Comment by JordanMartinez** [comment] 2017-03-17 01:02
@KnightPL, is this issue resolved?

**Comment by Chan1996** [comment] 2017-04-03 23:19
@JordanMartinez 
I check out all above your answers, but sadly I didn't solve my problem in the end...

I run the `XMLEditor Demo`. Actually, I just want to do one thing : 
> make the background `black` and the non-highlight text  `white`

So I modified the `xml-highlighting.css` like :
`
.text {
    -fx-fill: white;
}

.tagmark {
    -fx-fill: gray;
}
.anytag {
    -fx-fill: orangered;
}
.paren {
    -fx-fill: firebrick;
    -fx-font-weight: bold;
}
.attribute {
    -fx-fill: green;
}
.avalue {
    -fx-fill: green;
}

.comment {
	-fx-fill: mediumpurple;
}

.styled-text-area {
    -fx-background-color: black;
}
`

It worked, **BUT the line numbers became white, too**
Now I cant see them because its background is grey
![image](https://cloud.githubusercontent.com/assets/21203872/24634992/540f98fe-1903-11e7-9a31-b8e8f61bc541.png)

How can I solve this problem?

**Comment by JordanMartinez** [comment] 2017-04-04 00:22
Add a `lineno` styleclass entry to your CSS file:
````css
.lineno {
 -fx-background-color: black;
}
````
The CSS Reference Guide explains that one can style the `LineNumberFactory`'s returning `Node` by using that styleclass.

**Comment by Chan1996** [comment] 2017-04-04 00:37
@JordanMartinez 
It works , thank you very much !
BTW, it's a wonderful JavaFX lib

**Closed** 2017-05-28 02:20 UTC
Labels: question
