### ISSUE TITLE
It's possible to add a context menu into CodeArea?

### ISSUE THREAD

**Issue by ThallyssonKlein** [TomasMikula/RichTextFX#448] opened 2017-03-10 11:37 UTC
Hi there. I'm looking for a way to display line numbers on JavaFX TextArea and they pointed me to this library. I have already implemented the CodeArea into my interface, but I discovered a problem. My TextArea had a context menu, but when I tried to add it on CodeArea, did not work. So I would to know if it's possible to do it?

**Comment by kuc** [comment] 2017-03-10 14:48
It's possibile in `0.7-M3`

See #439

**Comment by ThallyssonKlein** [comment] 2017-03-12 17:28
Do you know to explain to me what I did wrong?

![image](https://cloud.githubusercontent.com/assets/16887598/23834137/10c62fd4-0730-11e7-8842-498f1945b706.png)

**Comment by JordanMartinez** [comment] 2017-03-13 17:24
@ThallyssonKlein It looks like your code is correct. However, could you explain why your code isn't working as expected? Is the menu not even showing up? Are you sure the code is even running?

**Comment by ThallyssonKlein** [comment] 2017-03-13 22:55
I could not even execute the code. The Eclipse is tell me that the parameter is wrong. I have analize the imports and sems that there not nothing wrong. See:

```
import org.fxmisc.wellbehaved.event.EventPattern;
import org.fxmisc.wellbehaved.event.InputMap;
import org.fxmisc.wellbehaved.event.Nodes;
import org.fxmisc.wellbehaved.event.template.InputMapTemplate;
```

**Comment by JordanMartinez** [comment] 2017-03-14 00:43
Strange....
Are you using Gradle to build the project? If so, perhaps you need to refresh your dependencies...

Regardless, can you post a reproducible demo? That might help us track down the issue.

**Comment by ThallyssonKlein** [comment] 2017-03-15 01:31
No, I don't using Gradle . But I'm using Maven. From what I've seen this method does not exist. So I think about the error is happening at pom.xml. Look:

	<dependency>
  		<groupId>org.fxmisc.richtext</groupId>
  		<artifactId>richtextfx</artifactId>
    	<version>0.4</version>
	</dependency>
	<dependency>
    	<groupId>org.fxmisc.wellbehaved</groupId>
    	<artifactId>WellBehavedFX</artifactId>
    	<version>0.1.1</version>
	</dependency>
	<dependency>
    	<groupId>org.fxmisc.wellbehaved</groupId>
    	<artifactId>wellbehavedfx</artifactId>
    	<version>0.3</version>
	</dependency>

**Comment by JordanMartinez** [comment] 2017-03-15 04:40
WellBehavedFX is listed twice....? And RichTextFX is a much older version that doesn't use the InputMap API in WellBehavedFX 0.3...
That's interesting...

**Comment by ThallyssonKlein** [comment] 2017-03-15 13:40
I'm sorry, I don't saw it. I removed the duplicated WellBehavedFX and the issue disappear. So, what's the RichTextFX version that use the InputMap API?

**Comment by JordanMartinez** [comment] 2017-03-15 15:16
That was introduced in [`0.7-M1`](https://github.com/TomasMikula/RichTextFX/releases/tag/v0.7-M1), but I would use at least [`0.7-M2`](https://github.com/TomasMikula/RichTextFX/releases/tag/0.7-M2) because of the added convenience methods as well as additional CSS.

**Comment by ThallyssonKlein** [comment] 2017-03-15 17:01
Thank you for all.

**Comment by JordanMartinez** [comment] 2017-03-17 01:01
If this issue is resolved, please close it @ThallyssonKlein.

**Comment by JordanMartinez** [comment] 2017-03-17 01:01
(wrong button pressed)

**Closed** 2017-03-17 01:06 UTC
