### ISSUE TITLE
CodeArea misidentifies click location

### ISSUE THREAD

**Issue by hwaite** [TomasMikula/RichTextFX#201] opened 2015-11-02 21:18 UTC
For a CodeArea inside of an 'Alert' dialog, mouse clicks do not move caret to proper location. Probably attributable to ignored border widths or something like that. On Windows 7 & JDK 1.8 u60, caret jumps to line closest to the *bottom* of cursor icon. CodeArea doesn't behave this way in parent window.

    public class Test extends Application {
        public static void main(String[] args) {launch(args);}

        public void start(Stage pStage) {
            pStage.setTitle("Test");

            final Pane root = new VBox();

            final String txt = String.join("\n", "1", "2", "3", "4", "5");
            root.getChildren().addAll(
                Stream.of(
                    new CodeArea() {{replaceText(txt);}}, new TextArea() {{setText(txt);}}
                ).map(
                    pNode -> new Button(pNode.getClass().getSuperclass().getName()) {
                        final Alert mAlert = new Alert(AlertType.NONE);
                        {
                            mAlert.getDialogPane().setContent(pNode);
                            mAlert.getDialogPane().getButtonTypes().addAll(
                                ButtonType.OK, ButtonType.CANCEL
                            );
                            setOnAction(pEvt -> mAlert.showAndWait());
                        }
                    }
                ).collect(Collectors.toList())
            );

            root.getChildren().addAll(
                new CodeArea() {{replaceText(txt);}},
                new TextArea() {{setText(txt);}},
                new TextField()
            );

            pStage.setScene(new Scene(root, 300, 250));
            pStage.show();
        }
    }

**Comment by TomasMikula** [comment] 2015-11-02 21:28
Hi, this is a duplicate of #196. See that issue for a workaround. I will close this as a duplicate.

**Closed by TomasMikula** 2015-11-02 21:28 UTC
