### ISSUE TITLE
Distorted Text

### ISSUE THREAD

**Issue by deepsidhu1313** [TomasMikula/RichTextFX#90] opened 2014-10-22 17:34 UTC
I am using RichTextFx library for code editor in my parallel computing framework. Sometimes i get distorted text in the whole text area. Is this problem bcz of JDK8u20 or from any bug in RichTextFX? Also when i press ctrl+z, Code written in codeArea gets clear. Is there any thing to prevent it from happening and adding a proper undo function? Also i will be very thankful to you if you suggest any tips to make a proper code editor for the framework. 

Thanks :-)  

![screenshot from 2014-10-22 22 51 45](https://cloud.githubusercontent.com/assets/7684338/4740770/4fb4fcae-5a10-11e4-8bf4-cffd13aa4734.png)

**Comment by TomasMikula** [comment] 2015-02-02 18:59
Closing this issue as a duplicate of #88.

**Closed by TomasMikula** 2015-02-02 18:59 UTC
Labels: duplicate

**Comment by RobertBColton** [comment] 2015-02-03 23:53
@TomasMikula I just want to confirm for you that the artifacts on the two words "License headers" in his screencap is also similar to what I saw with the HTML WebView JFX control. Especially when horizontally scrolling it would rip the bottom half of some sentences off and distort them, which directly contrasts with the other bugs that are more present with vertical scrolling. The bold letters look like they are missing Antialiasing.
