### ISSUE TITLE
Controls not recognized in Scene Builder 2.0

### ISSUE THREAD

**Issue by eidbadr** [TomasMikula/RichTextFX#177] opened 2015-09-07 15:07 UTC
Hello,

I want to use the RichTextFX in Scene Build, but they are not recognized. why?

![unbenannt](https://cloud.githubusercontent.com/assets/14164370/9719026/0a948c12-5581-11e5-9eda-ea39f128be8e.PNG)

And when I used a StyleClassedTextArea in Intellij I got the following error:

java.io.IOException: javafx.fxml.LoadException: 
/E:/B5807012_TP01528/all/java/zisupdate/src/java/resources/zisupdate.fxml

	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:92)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:80)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMDocument.<init>(FXOMDocument.java:95)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.updateFxomDocument(EditorController.java:2370)
	at com.oracle.javafx.scenebuilder.kit.editor.EditorController.setFxmlTextAndLocation(EditorController.java:655)
	at org.jetbrains.plugins.javaFX.sceneBuilder.SceneBuilderImpl.loadFile(SceneBuilderImpl.java:137)
	at org.jetbrains.plugins.javaFX.sceneBuilder.SceneBuilderImpl.create(SceneBuilderImpl.java:59)
	at org.jetbrains.plugins.javaFX.sceneBuilder.SceneBuilderImpl.access$000(SceneBuilderImpl.java:28)
	at org.jetbrains.plugins.javaFX.sceneBuilder.SceneBuilderImpl$1.run(SceneBuilderImpl.java:47)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$75/3956551.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$74/25598835.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
	at com.sun.glass.ui.win.WinApplication$$Lambda$63/30911611.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javafx.fxml.LoadException: 
/E:/B5807012_TP01528/all/java/zisupdate/src/java/resources/zisupdate.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2605)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2852)
	at javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2696)
	at javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2665)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2521)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2429)
	at com.oracle.javafx.scenebuilder.kit.fxom.FXOMLoader.load(FXOMLoader.java:89)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.fxmisc.richtext.StyleClassedTextArea
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2920)
	at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2909)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2850)
	... 23 more
![unbenannt2](https://cloud.githubusercontent.com/assets/14164370/9719231/c27acf7a-5582-11e5-825d-02e6420b3732.PNG)

**Comment by TomasMikula** [comment] 2015-09-07 16:59
Hi,

I don't use SceneBuilder myself and I don't know what it takes to make SceneBuilder work with RichTextFX. You are more likely to get an answer if you ask the SceneBuilder folks.

Best,
Tomas

**Comment by TomasMikula** [comment] 2015-11-23 19:27
Closing as this is not a RichTextFX problem.

**Closed by TomasMikula** 2015-11-23 19:27 UTC

**Comment by Neiko2002** [comment] 2022-05-20 19:49
I think it is actually a RichTextFX problem. There is nothing the SceneBuilder developers can do to make the RichTextFX components work. The changes have to be made in the RichTextFX code base. Therefore, I would like to reopen the issue in hopes that someone can take a look.

**Comment by Jugen** [comment] 2022-05-23 12:41
Download and import the RichtextFX **_fat_** jar into SceneBuilder and it'll work.
The latest version is available [here](https://github.com/FXMisc/RichTextFX#manual-download).

**Comment by Neiko2002** [comment] 2022-05-23 23:25
True to some extent, but not all classes get imported, like the StyleClassedTextField. So any FXML file containing this class gives an error message along these lines:

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.fxmisc.richtext.StyleClassedTextField

The same goes for the InlineCssTextField.

**Comment by Neiko2002** [comment] 2022-05-24 10:52
The new far jar works fine in SceneBuilder. Thank you very much.
